name: dart_object_extension
description: This plugin extends the functionality of the object class.
version: 0.0.2
homepage: https://github.com/JosephNK/dart_object_extension

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.1

  test: ^1.21.1
  build_runner: ^2.1.11
  source_gen_test: ^1.0.3

flutter:
