name: dart_object_extension
description: This plugin is an dart object extension plugin.
version: 0.0.1
homepage: https://github.com/JosephNK/dart_object_extension

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

#  build_test: ^2.1.5
  build_runner: ^2.1.11
#  source_gen_test: ^1.0.3

flutter:
