targets:
  $default:
    builders:
      dart_object_extension|copyWith:
        enabled: true

builders:
  copyWith:
    target: ":dart_object_extension"
    import: "package:dart_object_extension_gen/dart_object_extension_gen.dart"
    builder_factories: ["copyWith"]
    build_extensions: {".dart": ["copyWith.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]